# Generated by Django 6.0.2 on 2026-02-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('co2_saved_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_saved_litres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meals_equivalent', models.DecimalField(decimal_places=1, max_digits=8)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='donations.donation')),
            ],
        ),
    ]
