# Generated by Django 6.0.2 on 2026-02-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('food_type', models.CharField(choices=[('perishable', 'Perishable'), ('non_perishable', 'Non-Perishable'), ('cooked', 'Cooked Meal'), ('produce', 'Fresh Produce')], max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('expiry_time', models.DateTimeField()),
                ('pickup_address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('matched', 'Matched'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('expired', 'Expired')], default='available', max_length=20)),
                ('dietary_notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
